cask_args appdir: '/Applications'

tap 'caskroom/fonts'

brew 'kubernetes-helm'
brew 'kubectl'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'caffeine'
cask 'cyberduck'
cask 'docker'
cask 'dropbox'
cask 'font-hack-nerd-font'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'postman'
cask 'skitch'
cask 'slack'
cask 'sourcetree'
cask 'spectacle'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'visual-studio-code'
cask 'viscosity'
cask 'vlc'
cask 'whatsapp'
